import { Container, Header } from "@/components/shared"
import { Footer } from "@/components/shared/footer"
import { Metadata } from "next"
import { Suspense } from "react"

export const metadata: Metadata = {
  title: 'Super Pizza | Checkout',
  description: 'Generated by Next.js',
}

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
        <Container>
            <Suspense>
              <Header hasSearch={false} hasCartButton={false} className="border-gray-200" />
            </Suspense>
            {children}
            <Footer />
        </Container>
    </main>
  )
}
